# Generated by Django 6.0.3 on 2026-04-08 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0009_synccheckpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conversation_id", models.CharField(db_index=True, max_length=100)),
                ("chainlit_step_id", models.CharField(db_index=True, max_length=100)),
                (
                    "chainlit_feedback_id",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
                ),
                ("value", models.SmallIntegerField(choices=[(0, "Incorrect"), (1, "Correct")])),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="chatbot.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_message_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chatmessagefeedback",
            constraint=models.UniqueConstraint(
                fields=("user", "message"),
                name="unique_chat_feedback_per_user_message",
            ),
        ),
    ]
